# Generated by Django 5.2 on 2025-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Bwd_Packet_Length_Min', models.FloatField()),
                ('Bwd_Packet_Length_Std', models.FloatField()),
                ('Init_Win_bytes_forward', models.FloatField()),
                ('Init_Win_bytes_backward', models.FloatField()),
                ('Fwd_PSH_Flags', models.IntegerField()),
                ('Average_Packet_Size', models.FloatField()),
                ('PSH_Flag_Count', models.IntegerField()),
                ('Bwd_Packets_s', models.FloatField()),
                ('Bwd_Header_Length', models.FloatField()),
                ('Bwd_Packet_Length_Mean', models.FloatField()),
                ('Fwd_Header_Length_1', models.FloatField()),
                ('min_seg_size_forward', models.FloatField()),
                ('Bwd_Packet_Length_Max', models.FloatField()),
                ('Packet_Length_Variance', models.FloatField()),
                ('Fwd_Packet_Length_Max', models.FloatField()),
                ('Fwd_Packet_Length_Mean', models.FloatField()),
                ('Flow_Bytes_s', models.FloatField()),
                ('Fwd_IAT_Min', models.FloatField()),
                ('Total_Length_of_Fwd_Packets', models.FloatField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
